name: note_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  awesome_dialog: ^2.2.1
  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_search: ^5.0.2
  equatable: ^2.0.5
  firebase_auth: ^3.7.0
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  firebase_storage: ^10.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.4
  get_it: ^7.2.0
  google_sign_in: ^5.4.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  jiffy: ^5.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200


